### ISSUE TITLE
`keycloak-realm-operator` image not available

### ISSUE THREAD

**Issue by rassie** [keycloak/keycloak-realm-operator#5]
### Describe the bug

When following deployment instructions, an image `quay.io/keycloak/keycloak-realm-operator:latest` is requested by the Realm Operator deployment. This image is not available, the repository is empty.

### Version

20.x

### Expected behavior

Deployment succeeds, having pulled `quay.io/keycloak/keycloak-realm-operator:latest` successfully.

### Actual behavior

Image pull fails, deployment fails.

### How to Reproduce?

1. Observe image name in https://raw.githubusercontent.com/keycloak/keycloak-realm-operator/main/deploy/operator.yaml, which is recommended by the docs.
2. Try pulling `quay.io/keycloak/keycloak-realm-operator:latest`
3. Observe pull errors due to missing image.

**Comment by vmuzikar** [comment]
Thanks for the report. The image should be available now.
